spring:
  profiles:
    active: dev  # default to dev
  application:
    name: "documentstore"
  cloud:
    gcp:
        project-number: ${GCP_PROJECT_NUMBER:741672280176}
        project-id: ${GCP_PROJECT_ID:muditsahni-bb2eb}
        credentials:
            location: ${GOOGLE_APPLICATION_CREDENTIALS:unknown}
        firebase:
          credentials:
            location: ${FIREBASE_CREDENTIALS:unknown}
  security:
    filter:
      dispatcher-types: request,async

app:
  upload:
    max-files: 10
    max-file-size: 10485760  # 10MB in bytes
    allowed-types:
      - application/pdf

gcp:
  project-id: ${spring.cloud.gcp.project-id}
  service-account: ${GCP_SERVICE_ACCOUNT}
  region: ${GCP_REGION:asia-south1}  # Added region with default
  cloud-tasks:
    location: ${GCP_REGION:asia-south1}  # Required for Cloud Tasks
    queue: ${GCP_QUEUE_NAME:document-parser-queue}  # Required for Cloud Tasks

document-parser:
  name: "documentparser"
  projectNumber: ${spring.cloud.gcp.project-number}
  region: "asia-south2"
  uri: "api"
  version: "v1"
  upload: "upload"

logging:
  level:
    com.muditsahni.documentstore: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    okhttp3: DEBUG  # Enable for detailed HTTP logging
