package com.muditsahni.documentstore.config.documentparser

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(DocumentParserProperties::class)
class DocumentParserConfig